// Code generated by compylr. DO NOT EDIT.
package main

type IntStack struct {
	height int64
	slots  []int64
}

func NewIntStack() *IntStack {
	inst := &IntStack{
		height: 0,
		slots:  make([]int64, 0),
	}
	return inst
}

func (self *IntStack) depth() int64 {
	return self.height
}

func (self *IntStack) peek() int64 {
	if self.height == int64(0) {
		return int64(0)
	}
	return (self.slots)[(self.height - int64(1))]
}

func (self *IntStack) pop() int64 {
	if self.height == int64(0) {
		return int64(0)
	}
	self.height = (self.height - int64(1))
	return (self.slots)[self.height]
}

func (self *IntStack) push(value int64) {
	if self.height < int64(len(self.slots)) {
		self.slots[self.height] = value
	} else {
		self.slots = append(self.slots, value)
	}
	self.height = (self.height + int64(1))
}

type PrimeCache struct {
	hits  int64
	known map[int64]int64
}

func NewPrimeCache() *PrimeCache {
	inst := &PrimeCache{
		hits:  0,
		known: make(map[int64]int64),
	}
	return inst
}

func (self *PrimeCache) hitCount() int64 {
	return self.hits
}

func (self *PrimeCache) isPrime(n int64) bool {
	if n < int64(2) {
		return false
	}
	var d int64 = int64(2)
	for (d * d) <= n {
		if GoRem(n, d) == int64(0) {
			return false
		}
		d = (d + int64(1))
	}
	return true
}

func (self *PrimeCache) knownCount() int64 {
	return int64(len(self.known))
}

func (self *PrimeCache) nth(n int64) int64 {
	if n < int64(1) {
		return int64(0)
	}
	if func() bool { _, ok := (self.known)[n]; return ok }() {
		self.hits = (self.hits + int64(1))
		return (self.known)[n]
	}
	var found int64 = int64(0)
	var candidate int64 = int64(1)
	for found < n {
		candidate = (candidate + int64(1))
		if self.isPrime(candidate) {
			found = (found + int64(1))
		}
	}
	self.known[n] = candidate
	return candidate
}

type RunningStats struct {
	count   int64
	total   int64
	totalSq int64
}

func NewRunningStats() *RunningStats {
	inst := &RunningStats{
		count:   0,
		total:   0,
		totalSq: 0,
	}
	return inst
}

func (self *RunningStats) add(x int64) {
	self.count = (self.count + int64(1))
	self.total = (self.total + x)
	self.totalSq = (self.totalSq + (x * x))
}

func (self *RunningStats) currentMean() int64 {
	if self.count == int64(0) {
		return int64(0)
	}
	return GoFloorDiv(self.total, self.count)
}

func (self *RunningStats) currentVariance() int64 {
	if self.count == int64(0) {
		return int64(0)
	}
	var m int64 = self.currentMean()
	var meanSq int64 = GoFloorDiv(self.totalSq, self.count)
	var v int64 = (meanSq - (m * m))
	if v < int64(0) {
		return int64(0)
	}
	return v
}

type UnionFind struct {
	components int64
	parent     []int64
	rank       []int64
}

func NewUnionFind(size int64) *UnionFind {
	inst := &UnionFind{
		components: 0,
		parent:     make([]int64, 0),
		rank:       make([]int64, 0),
	}
	return inst
}

func (self *UnionFind) connected(p int64, q int64) bool {
	return (self.find(p) == self.find(q))
}

func (self *UnionFind) find(p int64) int64 {
	var root int64 = p
	for root != (self.parent)[root] {
		root = (self.parent)[root]
	}
	var curr int64 = p
	for curr != root {
		var next int64 = (self.parent)[curr]
		self.parent[curr] = root
		curr = next
	}
	return root
}

func (self *UnionFind) setCount() int64 {
	return self.components
}

func (self *UnionFind) union(p int64, q int64) {
	var rootP int64 = self.find(p)
	var rootQ int64 = self.find(q)
	if rootP == rootQ {
		return
	}
	if (self.rank)[rootP] < (self.rank)[rootQ] {
		self.parent[rootP] = rootQ
	} else {
		if (self.rank)[rootP] > (self.rank)[rootQ] {
			self.parent[rootQ] = rootP
		} else {
			self.parent[rootQ] = rootP
			self.rank[rootP] = ((self.rank)[rootP] + int64(1))
		}
	}
	self.components = (self.components - int64(1))
}

func averageOfCounts(counts []int64) int64 {
	if int64(len(counts)) == int64(0) {
		return int64(0)
	}
	var total int64 = int64(0)
	for _, count := range counts {
		total = (total + count)
	}
	return GoFloorDiv(total, int64(len(counts)))
}

func balanced(tokens []int64) bool {
	var stack *IntStack = NewIntStack()
	for _, token := range tokens {
		if token > int64(0) {
			stack.push(token)
		} else {
			if stack.depth() == int64(0) {
				return false
			}
			if (stack.pop() + token) != int64(0) {
				return false
			}
		}
	}
	return (stack.depth() == int64(0))
}

func bfsDistances(graph map[int64][]int64, start int64) map[int64]int64 {
	var distance map[int64]int64 = make(map[int64]int64)
	distance[start] = int64(0)
	var queue []int64 = nil
	queue = append(queue, start)
	var head int64 = int64(0)
	for head < int64(len(queue)) {
		var node int64 = (queue)[head]
		head = (head + int64(1))
		if !(func() bool { _, ok := (graph)[node]; return ok }()) {
			continue
		}
		var neighbours []int64 = (graph)[node]
		var currentDist int64 = (distance)[node]
		for _, neighbour := range neighbours {
			if func() bool { _, ok := (distance)[neighbour]; return ok }() {
				continue
			}
			distance[neighbour] = (currentDist + int64(1))
			queue = append(queue, neighbour)
		}
	}
	return distance
}

func binarySearch(xs []int64, target int64) int64 {
	var low int64 = int64(0)
	var high int64 = (int64(len(xs)) - int64(1))
	for low <= high {
		var mid int64 = GoFloorDiv((low + high), int64(2))
		if (xs)[mid] == target {
			return mid
		} else {
			if (xs)[mid] < target {
				low = (mid + int64(1))
			} else {
				high = (mid - int64(1))
			}
		}
	}
	return int64(-1)
}

func coinChange(coins []int64, amount int64) int64 {
	if amount <= int64(0) {
		return int64(0)
	}
	var infinity int64 = (amount + int64(1))
	var dp []int64 = nil
	dp = append(dp, int64(0))
	var a int64 = int64(1)
	for a <= amount {
		dp = append(dp, infinity)
		a = (a + int64(1))
	}
	for _, coin := range coins {
		var current int64 = coin
		for current <= amount {
			dp[current] = smaller((dp)[current], ((dp)[(current-coin)] + int64(1)))
			current = (current + int64(1))
		}
	}
	if (dp)[amount] >= infinity {
		return int64(-1)
	}
	return (dp)[amount]
}

func collatzLength(n int64) int64 {
	if n < int64(1) {
		return int64(0)
	}
	var steps int64 = int64(0)
	var current int64 = n
	for current != int64(1) {
		if GoRem(current, int64(2)) == int64(0) {
			current = GoFloorDiv(current, int64(2))
		} else {
			current = ((int64(3) * current) + int64(1))
		}
		steps = (steps + int64(1))
	}
	return steps
}

func componentCount(graph map[int64][]int64) int64 {
	var nodes []int64 = nodeList(graph)
	var visited map[int64]int64 = make(map[int64]int64)
	var count int64 = int64(0)
	for _, node := range nodes {
		if func() bool { _, ok := (visited)[node]; return ok }() {
			continue
		}
		count = (count + int64(1))
		var reached []int64 = depthFirstOrder(graph, node)
		for _, r := range reached {
			visited[r] = int64(1)
		}
	}
	return count
}

func copyOf(xs []int64) []int64 {
	var out []int64 = nil
	for _, x := range xs {
		out = append(out, x)
	}
	return out
}

func countPresent(words []string, wanted map[string]struct{}) int64 {
	var total int64 = int64(0)
	for _, word := range words {
		if func() bool { _, ok := (wanted)[word]; return ok }() {
			total = (total + int64(1))
		}
	}
	return total
}

func depthFirstOrder(graph map[int64][]int64, start int64) []int64 {
	var order []int64 = nil
	var seen map[int64]int64 = make(map[int64]int64)
	var stack []int64 = nil
	stack = append(stack, start)
	var top int64 = int64(1)
	for top > int64(0) {
		top = (top - int64(1))
		var node int64 = (stack)[top]
		if func() bool { _, ok := (seen)[node]; return ok }() {
			continue
		}
		seen[node] = int64(1)
		order = append(order, node)
		if !(func() bool { _, ok := (graph)[node]; return ok }()) {
			continue
		}
		var neighbours []int64 = (graph)[node]
		var index int64 = (int64(len(neighbours)) - int64(1))
		for index >= int64(0) {
			var neighbour int64 = (neighbours)[index]
			if !(func() bool { _, ok := (seen)[neighbour]; return ok }()) {
				if top < int64(len(stack)) {
					stack[top] = neighbour
				} else {
					stack = append(stack, neighbour)
				}
				top = (top + int64(1))
			}
			index = (index - int64(1))
		}
	}
	return order
}

func digitSum(n int64) int64 {
	var num int64 = n
	if num < int64(0) {
		num = -(num)
	}
	var sum int64 = int64(0)
	for num > int64(0) {
		sum = (sum + GoRem(num, int64(10)))
		num = GoFloorDiv(num, int64(10))
	}
	return sum
}

func divide(a int64, b int64) struct {
	F0 int64
	F1 int64
} {
	return struct {
		F0 int64
		F1 int64
	}{F0: GoFloorDiv(a, b), F1: GoRem(a, b)}
}

func editDistance(left []string, right []string) int64 {
	var rows int64 = int64(len(left))
	var columns int64 = int64(len(right))
	var table [][]int64 = tableOfZeros((rows + int64(1)), (columns + int64(1)))
	var i int64 = int64(0)
	for i <= rows {
		(table)[i][int64(0)] = i
		i = (i + int64(1))
	}
	var j int64 = int64(0)
	for j <= columns {
		(table)[int64(0)][j] = j
		j = (j + int64(1))
	}
	i = int64(1)
	for i <= rows {
		j = int64(1)
		for j <= columns {
			if (left)[(i-int64(1))] == (right)[(j-int64(1))] {
				(table)[i][j] = ((table)[(i - int64(1))])[(j - int64(1))]
			} else {
				var best int64 = smaller(((table)[(i - int64(1))])[j], ((table)[i])[(j-int64(1))])
				(table)[i][j] = (smaller(best, ((table)[(i - int64(1))])[(j-int64(1))]) + int64(1))
			}
			j = (j + int64(1))
		}
		i = (i + int64(1))
	}
	return ((table)[rows])[columns]
}

func extremes(xs []int64) struct {
	F0 int64
	F1 int64
} {
	if int64(len(xs)) == int64(0) {
		return struct {
			F0 int64
			F1 int64
		}{F0: int64(0), F1: int64(0)}
	}
	var low int64 = (xs)[int64(0)]
	var high int64 = (xs)[int64(0)]
	var i int64 = int64(1)
	for i < int64(len(xs)) {
		var val int64 = (xs)[i]
		if val < low {
			low = val
		}
		if val > high {
			high = val
		}
		i = (i + int64(1))
	}
	return struct {
		F0 int64
		F1 int64
	}{F0: low, F1: high}
}

func floorDivide(a int64, b int64) int64 {
	return GoFloorDiv(a, b)
}

func gcd(a int64, b int64) int64 {
	var x int64 = a
	var y int64 = b
	if x < int64(0) {
		x = -(x)
	}
	if y < int64(0) {
		y = -(y)
	}
	for y != int64(0) {
		var held int64 = y
		y = GoRem(x, y)
		x = held
	}
	return x
}

func insertionSort(xs []int64) []int64 {
	var out []int64 = copyOf(xs)
	var i int64 = int64(1)
	for i < int64(len(out)) {
		var key int64 = (out)[i]
		var j int64 = (i - int64(1))
		for j >= int64(0) {
			if (out)[j] > key {
				out[(j + int64(1))] = (out)[j]
				j = (j - int64(1))
			} else {
				break
			}
		}
		out[(j + int64(1))] = key
		i = (i + int64(1))
	}
	return out
}

func integerSqrt(n int64) int64 {
	if n < int64(0) {
		return int64(-1)
	}
	if n < int64(2) {
		return n
	}
	var x int64 = n
	var y int64 = GoFloorDiv((x + int64(1)), int64(2))
	for y < x {
		x = y
		y = GoFloorDiv((x + GoFloorDiv(n, x)), int64(2))
	}
	return x
}

func isPalindrome(chars []string) bool {
	var left int64 = int64(0)
	var right int64 = (int64(len(chars)) - int64(1))
	for left < right {
		if (chars)[left] != (chars)[right] {
			return false
		}
		left = (left + int64(1))
		right = (right - int64(1))
	}
	return true
}

func isPrime(n int64) bool {
	if n < int64(2) {
		return false
	}
	var d int64 = int64(2)
	for (d * d) <= n {
		if GoRem(n, d) == int64(0) {
			return false
		}
		d = (d + int64(1))
	}
	return true
}

func isSorted(xs []int64) bool {
	var i int64 = int64(1)
	for i < int64(len(xs)) {
		if (xs)[(i-int64(1))] > (xs)[i] {
			return false
		}
		i = (i + int64(1))
	}
	return true
}

func iterativeNotDivisible(divisible bool) bool {
	if divisible {
		return false
	}
	return true
}

func iterativeNthPrime(n int64) int64 {
	if n < int64(1) {
		return int64(0)
	}
	var found []int64 = iterativePrimesUpToCount(n)
	return (found)[(n - int64(1))]
}

func iterativePrimesUpToCount(n int64) []int64 {
	var found []int64 = nil
	var candidate int64 = int64(2)
	for int64(len(found)) < n {
		var divisible bool = false
		for _, p := range found {
			if (p * p) > candidate {
				break
			}
			if GoRem(candidate, p) == int64(0) {
				divisible = true
				break
			}
		}
		if iterativeNotDivisible(divisible) {
			found = append(found, candidate)
		}
		candidate = (candidate + int64(1))
	}
	return found
}

func knapsack(weights []int64, values []int64, capacity int64) int64 {
	var n int64 = int64(len(weights))
	var table [][]int64 = tableOfZeros((n + int64(1)), (capacity + int64(1)))
	var i int64 = int64(1)
	for i <= n {
		var w int64 = (weights)[(i - int64(1))]
		var v int64 = (values)[(i - int64(1))]
		var c int64 = int64(0)
		for c <= capacity {
			if w <= c {
				(table)[i][c] = larger(((table)[(i - int64(1))])[c], (((table)[(i - int64(1))])[(c-w)] + v))
			} else {
				(table)[i][c] = ((table)[(i - int64(1))])[c]
			}
			c = (c + int64(1))
		}
		i = (i + int64(1))
	}
	return ((table)[n])[capacity]
}

func larger(a int64, b int64) int64 {
	if a > b {
		return a
	}
	return b
}

func lcm(a int64, b int64) int64 {
	if a == int64(0) {
		return int64(0)
	}
	var product int64 = (a * b)
	if product < int64(0) {
		product = -(product)
	}
	return GoFloorDiv(product, gcd(a, b))
}

func longestCommonSubsequence(left []int64, right []int64) int64 {
	var rows int64 = int64(len(left))
	var columns int64 = int64(len(right))
	var table [][]int64 = tableOfZeros((rows + int64(1)), (columns + int64(1)))
	var i int64 = int64(1)
	for i <= rows {
		var j int64 = int64(1)
		for j <= columns {
			if (left)[(i-int64(1))] == (right)[(j-int64(1))] {
				(table)[i][j] = (((table)[(i - int64(1))])[(j-int64(1))] + int64(1))
			} else {
				(table)[i][j] = larger(((table)[(i - int64(1))])[j], ((table)[i])[(j-int64(1))])
			}
			j = (j + int64(1))
		}
		i = (i + int64(1))
	}
	return ((table)[rows])[columns]
}

func matrixMultiply(a [][]int64, b [][]int64) [][]int64 {
	if int64(len(a)) == int64(0) {
		return nil
	}
	var rowsA int64 = int64(len(a))
	var colsA int64 = int64(len((a)[int64(0)]))
	var colsB int64 = int64(len((b)[int64(0)]))
	var out [][]int64 = tableOfZeros(rowsA, colsB)
	var i int64 = int64(0)
	for i < rowsA {
		var j int64 = int64(0)
		for j < colsB {
			var sum int64 = int64(0)
			var k int64 = int64(0)
			for k < colsA {
				sum = (sum + (((a)[i])[k] * ((b)[k])[j]))
				k = (k + int64(1))
			}
			(out)[i][j] = sum
			j = (j + int64(1))
		}
		i = (i + int64(1))
	}
	return out
}

func matrixTrace(m [][]int64) int64 {
	var trace int64 = int64(0)
	var i int64 = int64(0)
	for i < int64(len(m)) {
		if i < int64(len((m)[i])) {
			trace = (trace + ((m)[i])[i])
		}
		i = (i + int64(1))
	}
	return trace
}

func matrixTranspose(m [][]int64) [][]int64 {
	if int64(len(m)) == int64(0) {
		return nil
	}
	var rows int64 = int64(len(m))
	var cols int64 = int64(len((m)[int64(0)]))
	var out [][]int64 = tableOfZeros(cols, rows)
	var i int64 = int64(0)
	for i < rows {
		var j int64 = int64(0)
		for j < cols {
			(out)[j][i] = ((m)[i])[j]
			j = (j + int64(1))
		}
		i = (i + int64(1))
	}
	return out
}

func maxSubarraySum(xs []int64) int64 {
	if int64(len(xs)) == int64(0) {
		return int64(0)
	}
	var maxSoFar int64 = (xs)[int64(0)]
	var currentMax int64 = (xs)[int64(0)]
	var i int64 = int64(1)
	for i < int64(len(xs)) {
		var x int64 = (xs)[i]
		currentMax = larger(x, (currentMax + x))
		maxSoFar = larger(maxSoFar, currentMax)
		i = (i + int64(1))
	}
	return maxSoFar
}

func mean(xs []int64) int64 {
	if int64(len(xs)) == int64(0) {
		return int64(0)
	}
	var total int64 = int64(0)
	for _, x := range xs {
		total = (total + x)
	}
	return GoFloorDiv(total, int64(len(xs)))
}

func merge(left []int64, right []int64) []int64 {
	var out []int64 = nil
	var i int64 = int64(0)
	var j int64 = int64(0)
	for i < int64(len(left)) {
		if j >= int64(len(right)) {
			break
		}
		if (left)[i] <= (right)[j] {
			out = append(out, (left)[i])
			i = (i + int64(1))
		} else {
			out = append(out, (right)[j])
			j = (j + int64(1))
		}
	}
	for i < int64(len(left)) {
		out = append(out, (left)[i])
		i = (i + int64(1))
	}
	for j < int64(len(right)) {
		out = append(out, (right)[j])
		j = (j + int64(1))
	}
	return out
}

func mergeSort(xs []int64) []int64 {
	if int64(len(xs)) <= int64(1) {
		return copyOf(xs)
	}
	var mid int64 = GoFloorDiv(int64(len(xs)), int64(2))
	var left []int64 = nil
	var i int64 = int64(0)
	for i < mid {
		left = append(left, (xs)[i])
		i = (i + int64(1))
	}
	var right []int64 = nil
	for i < int64(len(xs)) {
		right = append(right, (xs)[i])
		i = (i + int64(1))
	}
	return merge(mergeSort(left), mergeSort(right))
}

func mostCommon(words []string) string {
	var counts map[string]int64 = wordCount(words)
	var best string = ""
	var bestCount int64 = int64(0)
	for word := range counts {
		var count int64 = (counts)[word]
		if count > bestCount {
			best = word
			bestCount = count
		} else {
			if count == bestCount {
				if best == "" {
					best = word
				}
			}
		}
	}
	return best
}

func nodeList(graph map[int64][]int64) []int64 {
	var seen map[int64]int64 = make(map[int64]int64)
	var raw []int64 = nil
	for node := range graph {
		if !(func() bool { _, ok := (seen)[node]; return ok }()) {
			seen[node] = int64(1)
			raw = append(raw, node)
		}
		var neighbours []int64 = (graph)[node]
		for _, neighbour := range neighbours {
			if func() bool { _, ok := (seen)[neighbour]; return ok }() {
				continue
			}
			seen[neighbour] = int64(1)
			raw = append(raw, neighbour)
		}
	}
	return mergeSort(raw)
}

func normalize(xs []int64) []int64 {
	if int64(len(xs)) == int64(0) {
		return nil
	}
	var avg int64 = mean(xs)
	var sd int64 = standardDeviation(xs)
	if sd == int64(0) {
		var zeroes []int64 = nil
		var i int64 = int64(0)
		for i < int64(len(xs)) {
			zeroes = append(zeroes, int64(0))
			i = (i + int64(1))
		}
		return zeroes
	}
	var out []int64 = nil
	for _, x := range xs {
		out = append(out, GoFloorDiv((x-avg), sd))
	}
	return out
}

func power(base int64, exponent int64) int64 {
	if exponent < int64(0) {
		return int64(0)
	}
	var result int64 = int64(1)
	var b int64 = base
	var e int64 = exponent
	for e > int64(0) {
		if GoRem(e, int64(2)) == int64(1) {
			result = (result * b)
		}
		e = GoFloorDiv(e, int64(2))
		if e > int64(0) {
			b = (b * b)
		}
	}
	return result
}

func recursiveIsPrime(n int64) bool {
	if n < int64(2) {
		return false
	}
	var d int64 = int64(2)
	for (d * d) <= n {
		if GoRem(n, d) == int64(0) {
			return false
		}
		d = (d + int64(1))
	}
	return true
}

func recursiveNextPrime(after int64) int64 {
	var candidate int64 = (after + int64(1))
	var found int64 = int64(0)
	for found == int64(0) {
		if recursiveIsPrime(candidate) {
			found = candidate
		}
		candidate = (candidate + int64(1))
	}
	return found
}

func recursiveNthPrime(n int64) int64 {
	if n < int64(1) {
		return int64(0)
	}
	return recursiveNthPrimeFrom(n, int64(1))
}

func recursiveNthPrimeFrom(remaining int64, current int64) int64 {
	if remaining < int64(1) {
		return current
	}
	return recursiveNthPrimeFrom((remaining - int64(1)), recursiveNextPrime(current))
}

func remainder(a int64, b int64) int64 {
	return GoRem(a, b)
}

func selectionSort(xs []int64) []int64 {
	var out []int64 = copyOf(xs)
	var i int64 = int64(0)
	for i < int64(len(out)) {
		var smallest int64 = i
		var j int64 = (i + int64(1))
		for j < int64(len(out)) {
			if (out)[j] < (out)[smallest] {
				smallest = j
			}
			j = (j + int64(1))
		}
		var held int64 = (out)[i]
		out[i] = (out)[smallest]
		out[smallest] = held
		i = (i + int64(1))
	}
	return out
}

func sieve(limit int64) []int64 {
	if limit < int64(3) {
		return nil
	}
	var isP []bool = nil
	var i int64 = int64(0)
	for i <= limit {
		isP = append(isP, true)
		i = (i + int64(1))
	}
	isP[int64(0)] = false
	isP[int64(1)] = false
	var p int64 = int64(2)
	for (p * p) <= limit {
		if (isP)[p] {
			var multiple int64 = (p * p)
			for multiple <= limit {
				isP[multiple] = false
				multiple = (multiple + p)
			}
		}
		p = (p + int64(1))
	}
	var primes []int64 = nil
	var n int64 = int64(2)
	for n <= limit {
		if (isP)[n] {
			primes = append(primes, n)
		}
		n = (n + int64(1))
	}
	return primes
}

func smaller(a int64, b int64) int64 {
	if a < b {
		return a
	}
	return b
}

func squareRoot(value int64) int64 {
	if value <= int64(0) {
		return int64(0)
	}
	var guess int64 = value
	var step int64 = int64(0)
	for step < int64(40) {
		guess = GoFloorDiv((guess + GoFloorDiv(value, guess)), int64(2))
		step = (step + int64(1))
	}
	return guess
}

func standardDeviation(xs []int64) int64 {
	return squareRoot(variance(xs))
}

func tableOfZeros(rows int64, columns int64) [][]int64 {
	var table [][]int64 = nil
	var r int64 = int64(0)
	for r < rows {
		var line []int64 = nil
		var c int64 = int64(0)
		for c < columns {
			line = append(line, int64(0))
			c = (c + int64(1))
		}
		table = append(table, line)
		r = (r + int64(1))
	}
	return table
}

func toBase(n int64, base int64) []int64 {
	var current int64 = n
	if current < int64(0) {
		current = -(current)
	}
	var backwards []int64 = nil
	if current == int64(0) {
		backwards = append(backwards, int64(0))
	}
	for current > int64(0) {
		var split struct {
			F0 int64
			F1 int64
		} = divide(current, base)
		backwards = append(backwards, split.F1)
		current = split.F0
	}
	var digits []int64 = nil
	var index int64 = (int64(len(backwards)) - int64(1))
	for index >= int64(0) {
		digits = append(digits, (backwards)[index])
		index = (index - int64(1))
	}
	return digits
}

func topologicalSort(graph map[int64][]int64) []int64 {
	var inDegree map[int64]int64 = make(map[int64]int64)
	var nodes []int64 = nodeList(graph)
	for _, n := range nodes {
		inDegree[n] = int64(0)
	}
	for u := range graph {
		var neighbours []int64 = (graph)[u]
		for _, v := range neighbours {
			inDegree[v] = ((inDegree)[v] + int64(1))
		}
	}
	var ready []int64 = nil
	for _, n := range nodes {
		if (inDegree)[n] == int64(0) {
			ready = append(ready, n)
		}
	}
	var order []int64 = nil
	var head int64 = int64(0)
	for head < int64(len(ready)) {
		var u int64 = (ready)[head]
		head = (head + int64(1))
		order = append(order, u)
		if func() bool { _, ok := (graph)[u]; return ok }() {
			var neighbours []int64 = (graph)[u]
			for _, v := range neighbours {
				var deg int64 = ((inDegree)[v] - int64(1))
				inDegree[v] = deg
				if deg == int64(0) {
					ready = append(ready, v)
				}
			}
		}
	}
	if int64(len(order)) != int64(len(nodes)) {
		return nil
	}
	return order
}

func uniqueWords(words []string) []string {
	var seen map[string]int64 = make(map[string]int64)
	var out []string = nil
	for _, word := range words {
		if func() bool { _, ok := (seen)[word]; return ok }() {
			continue
		}
		seen[word] = int64(1)
		out = append(out, word)
	}
	return out
}

func variance(xs []int64) int64 {
	if int64(len(xs)) == int64(0) {
		return int64(0)
	}
	var centre int64 = mean(xs)
	var total int64 = int64(0)
	for _, x := range xs {
		var deviation int64 = (x - centre)
		total = (total + (deviation * deviation))
	}
	return GoFloorDiv(total, int64(len(xs)))
}

func vowelLetters() map[string]struct{} {
	var s map[string]struct{} = make(map[string]struct{})
	s["a"] = struct{}{}
	s["e"] = struct{}{}
	s["i"] = struct{}{}
	s["o"] = struct{}{}
	s["u"] = struct{}{}
	return s
}

func wordCount(words []string) map[string]int64 {
	var counts map[string]int64 = make(map[string]int64)
	for _, word := range words {
		if func() bool { _, ok := (counts)[word]; return ok }() {
			counts[word] = ((counts)[word] + int64(1))
		} else {
			counts[word] = int64(1)
		}
	}
	return counts
}
