export function averageOfCounts(counts: number): number;
export function balanced(tokens: number): number;
export function bfsDistances(graph: number, start: number): number;
export function binarySearch(xs: number, target: number): number;
export function coinChange(coins: number, amount: number): number;
export function collatzLength(n: number): number;
export function componentCount(graph: number): number;
export function copyOf(xs: number): number;
export function countPresent(words: number, wanted: number): number;
export function depthFirstOrder(graph: number, start: number): number;
export function digitSum(n: number): number;
export function divide(a: number, b: number): number;
export function editDistance(left: number, right: number): number;
export function extremes(xs: number): number;
export function floorDivide(a: number, b: number): number;
export function gcd(a: number, b: number): number;
export function insertionSort(xs: number): number;
export function integerSqrt(n: number): number;
export function isPalindrome(chars: number): number;
export function isPrime(n: number): number;
export function isSorted(xs: number): number;
export function iterativeNotDivisible(divisible: number): number;
export function iterativeNthPrime(n: number): number;
export function iterativePrimesUpToCount(n: number): number;
export function knapsack(weights: number, values: number, capacity: number): number;
export function larger(a: number, b: number): number;
export function lcm(a: number, b: number): number;
export function longestCommonSubsequence(left: number, right: number): number;
export function matrixMultiply(a: number, b: number): number;
export function matrixTrace(m: number): number;
export function matrixTranspose(m: number): number;
export function maxSubarraySum(xs: number): number;
export function mean(xs: number): number;
export function merge(left: number, right: number): number;
export function mergeSort(xs: number): number;
export function mostCommon(words: number): number;
export function nodeList(graph: number): number;
export function normalize(xs: number): number;
export function power(base: number, exponent: number): number;
export function recursiveIsPrime(n: number): number;
export function recursiveNextPrime(after: number): number;
export function recursiveNthPrime(n: number): number;
export function recursiveNthPrimeFrom(remaining: number, current: number): number;
export function remainder(a: number, b: number): number;
export function selectionSort(xs: number): number;
export function sieve(limit: number): number;
export function smaller(a: number, b: number): number;
export function squareRoot(value: number): number;
export function standardDeviation(xs: number): number;
export function tableOfZeros(rows: number, columns: number): number;
export function toBase(n: number, base: number): number;
export function topologicalSort(graph: number): number;
export function uniqueWords(words: number): number;
export function variance(xs: number): number;
export function vowelLetters(): number;
export function wordCount(words: number): number;
