[package]
name = "compylr"
version = "0.1.0"
edition = "2024"

[dependencies]
ruff_python_ast = { version = "0.0.0", path = "vendored/ruff/crates/ruff_python_ast" }
ruff_python_parser = { version = "0.0.0", path = "vendored/ruff/crates/ruff_python_parser" }
ruff_source_file = { version = "0.0.0", path = "vendored/ruff/crates/ruff_source_file" }
ruff_text_size = { version = "0.0.0", path = "vendored/ruff/crates/ruff_text_size" }

[dev-dependencies]
insta = "1.35.1"
