// Generated by compylr. Do not edit: regenerated from the IR on every rebuild.
#![allow(
    unused_parens,
    non_snake_case,
    unused_variables,
    dead_code,
    unused_imports,
    unused_assignments
)]

use pyo3::prelude::*;

pub mod bindings;
pub mod compat;
pub mod generated;

#[pymodule]
fn compylr_generated_ef5b5f0fa0049bdd_a0cdd1db(m: &Bound<'_, PyModule>) -> PyResult<()> {
    bindings::register(m)
}
