//! Rendering compylr IR into Go source code.

use std::fmt::Write as _;

use compylr_ir::{BinOp, Class, DivMode, Expr, Function, Literal, Stmt, Ty, Unit};

use crate::types::{go_ident, go_ty};

/// Render a complete Unit as generated.go source text.
pub fn emit_go_unit(unit: &Unit) -> String {
    let mut out = String::new();
    writeln!(out, "// Code generated by compylr. DO NOT EDIT.").unwrap();
    writeln!(out, "package main\n").unwrap();
    writeln!(out, "import (").unwrap();
    writeln!(out, "\t\"fmt\"").unwrap();
    writeln!(out, "\t\"errors\"").unwrap();
    writeln!(out, ")\n").unwrap();

    // Emit Classes
    for class in unit.classes() {
        emit_class(class, &mut out);
    }

    // Emit Functions
    for function in unit.functions() {
        emit_function(function, &mut out);
    }

    out
}

fn emit_class(class: &Class, out: &mut String) {
    let class_name = go_ident(&class.name);

    // Struct definition
    writeln!(out, "type {} struct {{", class_name).unwrap();
    for attr in &class.attributes {
        writeln!(out, "\t{} {}", go_ident(&attr.name), go_ty(&attr.ty)).unwrap();
    }
    writeln!(out, "}}\n").unwrap();

    // Constructor
    let params_str = class
        .attributes
        .iter()
        .map(|a| format!("{} {}", go_ident(&a.name), go_ty(&a.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "func New{}({}) (*{}, error) {{",
        class_name, params_str, class_name
    )
    .unwrap();
    writeln!(out, "\tinst := &{}{{", class_name).unwrap();
    for attr in &class.attributes {
        let name = go_ident(&attr.name);
        writeln!(out, "\t\t{}: {},", name, name).unwrap();
    }
    writeln!(out, "\t}}").unwrap();
    writeln!(out, "\treturn inst, nil").unwrap();
    writeln!(out, "}}\n").unwrap();

    // Methods
    for method in class.methods.values() {
        emit_method(&class_name, method, out);
    }
}

fn emit_method(class_name: &str, method: &Function, out: &mut String) {
    let method_name = go_ident(&method.name);
    let params_str = method
        .params
        .iter()
        .map(|p| format!("{} {}", go_ident(&p.name), go_ty(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let ret_str = if method.ret == Ty::Unit {
        "error".to_string()
    } else {
        format!("({}, error)", go_ty(&method.ret))
    };

    writeln!(
        out,
        "func (self *{}) {}({}) {} {{",
        class_name, method_name, params_str, ret_str
    )
    .unwrap();
    for stmt in &method.body {
        emit_stmt(stmt, out, 1, method.ret == Ty::Unit);
    }
    if method.ret == Ty::Unit
        && !method
            .body
            .iter()
            .any(|s| matches!(s, Stmt::Return(_) | Stmt::ReturnUnit))
    {
        writeln!(out, "\treturn nil").unwrap();
    }
    writeln!(out, "}}\n").unwrap();
}

fn emit_function(function: &Function, out: &mut String) {
    let fn_name = go_ident(&function.name);
    let params_str = function
        .params
        .iter()
        .map(|p| format!("{} {}", go_ident(&p.name), go_ty(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let ret_str = if function.ret == Ty::Unit {
        "error".to_string()
    } else {
        format!("({}, error)", go_ty(&function.ret))
    };

    writeln!(out, "func {}({}) {} {{", fn_name, params_str, ret_str).unwrap();
    for stmt in &function.body {
        emit_stmt(stmt, out, 1, function.ret == Ty::Unit);
    }
    if function.ret == Ty::Unit
        && !function
            .body
            .iter()
            .any(|s| matches!(s, Stmt::Return(_) | Stmt::ReturnUnit))
    {
        writeln!(out, "\treturn nil").unwrap();
    }
    writeln!(out, "}}\n").unwrap();
}

fn emit_stmt(stmt: &Stmt, out: &mut String, indent: usize, is_unit_ret: bool) {
    let ind = "\t".repeat(indent);
    match stmt {
        Stmt::Bind { name, ty, value } => {
            writeln!(
                out,
                "{}var {} {} = {}",
                ind,
                go_ident(name),
                go_ty(ty),
                emit_expr(value)
            )
            .unwrap();
        }
        Stmt::Assign { name, value, .. } => {
            writeln!(out, "{}{} = {}", ind, go_ident(name), emit_expr(value)).unwrap();
        }
        Stmt::SetAttr {
            object,
            name,
            value,
            ..
        } => {
            writeln!(
                out,
                "{}{}.{} = {}",
                ind,
                emit_expr(object),
                go_ident(name),
                emit_expr(value)
            )
            .unwrap();
        }
        Stmt::SetItem {
            collection,
            index,
            value,
        } => {
            writeln!(
                out,
                "{}{}[{}] = {}",
                ind,
                emit_expr(collection),
                emit_expr(index),
                emit_expr(value)
            )
            .unwrap();
        }
        Stmt::Append { sequence, value } => {
            let t = emit_expr(sequence);
            writeln!(out, "{}{} = append({}, {})", ind, t, t, emit_expr(value)).unwrap();
        }
        Stmt::Return(expr) => {
            writeln!(out, "{}return {}, nil", ind, emit_expr(expr)).unwrap();
        }
        Stmt::ReturnUnit => {
            if is_unit_ret {
                writeln!(out, "{}return nil", ind).unwrap();
            } else {
                writeln!(out, "{}return struct{{}}{{}}, nil", ind).unwrap();
            }
        }
        Stmt::If {
            test,
            then,
            otherwise,
        } => {
            writeln!(out, "{}if {} {{", ind, emit_expr(test)).unwrap();
            for s in then {
                emit_stmt(s, out, indent + 1, is_unit_ret);
            }
            if !otherwise.is_empty() {
                writeln!(out, "{}}} else {{", ind).unwrap();
                for s in otherwise {
                    emit_stmt(s, out, indent + 1, is_unit_ret);
                }
            }
            writeln!(out, "{}}}", ind).unwrap();
        }
        Stmt::While { test, body } => {
            writeln!(out, "{}for {} {{", ind, emit_expr(test)).unwrap();
            for s in body {
                emit_stmt(s, out, indent + 1, is_unit_ret);
            }
            writeln!(out, "{}}}", ind).unwrap();
        }
        Stmt::For {
            name, iter, body, ..
        } => {
            writeln!(
                out,
                "{}for _, {} := range {} {{",
                ind,
                go_ident(name),
                emit_expr(iter)
            )
            .unwrap();
            for s in body {
                emit_stmt(s, out, indent + 1, is_unit_ret);
            }
            writeln!(out, "{}}}", ind).unwrap();
        }
        Stmt::Break => {
            writeln!(out, "{}break", ind).unwrap();
        }
        Stmt::Continue => {
            writeln!(out, "{}continue", ind).unwrap();
        }
        Stmt::Effect(expr) => {
            writeln!(out, "{}_ = {}", ind, emit_expr(expr)).unwrap();
        }
    }
}

fn emit_expr(expr: &Expr) -> String {
    match expr {
        Expr::Literal(lit) => match lit {
            Literal::Int(i) => format!("int64({})", i),
            Literal::Float(f) => format!("float64({:?})", f64::from_bits(*f)),
            Literal::Bool(b) => format!("{}", b),
            Literal::Str(s) => format!("{:?}", s),
        },
        Expr::Name(n) => {
            if n == "self" {
                "self".to_string()
            } else {
                go_ident(n)
            }
        }
        Expr::Neg { value, .. } => format!("-({})", emit_expr(value)),
        Expr::Not(e) => format!("!({})", emit_expr(e)),
        Expr::ToFloat(e) => format!("float64({})", emit_expr(e)),
        Expr::Binary { op, left, right } => {
            let l = emit_expr(left);
            let r = emit_expr(right);
            match op {
                BinOp::Add { .. } => format!("({} + {})", l, r),
                BinOp::Sub { .. } => format!("({} - {})", l, r),
                BinOp::Mul { .. } => format!("({} * {})", l, r),
                BinOp::Div {
                    mode: DivMode::Integer(_),
                    ..
                } => {
                    format!(
                        "func() int64 {{ v, _ := GoFloorDiv({}, {}); return v }}()",
                        l, r
                    )
                }
                BinOp::Div { .. } => format!("({} / {})", l, r),
                BinOp::Rem { .. } => {
                    format!("func() int64 {{ v, _ := GoRem({}, {}); return v }}()", l, r)
                }
                BinOp::Eq => format!("({} == {})", l, r),
                BinOp::NotEq => format!("({} != {})", l, r),
                BinOp::Lt => format!("({} < {})", l, r),
                BinOp::LtE => format!("({} <= {})", l, r),
                BinOp::Gt => format!("({} > {})", l, r),
                BinOp::GtE => format!("({} >= {})", l, r),
            }
        }
        Expr::Subscript { base, index, .. } => {
            format!(
                "func() any {{ v, _ := GoSubscript({}, {}); return v }}()",
                emit_expr(base),
                emit_expr(index)
            )
        }
        Expr::Attribute { object, name } => format!("{}.{}", emit_expr(object), go_ident(name)),
        Expr::Len { value, .. } => format!("int64(len({}))", emit_expr(value)),
        Expr::Call { callee, args } => {
            let args_str = args.iter().map(emit_expr).collect::<Vec<_>>().join(", ");
            format!(
                "func() any {{ v, _ := {}({}); return v }}()",
                go_ident(callee),
                args_str
            )
        }
        Expr::MethodCall {
            receiver,
            method,
            args,
            ..
        } => {
            let args_str = args.iter().map(emit_expr).collect::<Vec<_>>().join(", ");
            format!(
                "func() any {{ v, _ := {}.{}({}); return v }}()",
                emit_expr(receiver),
                go_ident(method),
                args_str
            )
        }
        Expr::Construct { class, args } => {
            let args_str = args.iter().map(emit_expr).collect::<Vec<_>>().join(", ");
            format!(
                "func() *{} {{ v, _ := New{}({}); return v }}()",
                go_ident(class),
                go_ident(class),
                args_str
            )
        }
        Expr::ListLit(elements) => {
            let elems_str = elements
                .iter()
                .map(emit_expr)
                .collect::<Vec<_>>()
                .join(", ");
            format!("[]int64{{ {} }}", elems_str)
        }
        Expr::TupleLit(elements) => {
            let fields = elements
                .iter()
                .enumerate()
                .map(|(i, e)| format!("F{}: {}", i, emit_expr(e)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("struct {{ {} }}", fields)
        }
        _ => "/* unsupported expr */".to_string(),
    }
}
