//! Rendering compylr IR into Go source code.

use std::fmt::Write as _;

use compylr_ir::{BinOp, Class, DivMode, Expr, Function, Literal, Stmt, Ty, Unit};

use crate::types::{go_ident, go_ty};

/// Render a complete Unit as generated.go source text.
pub fn emit_go_unit(unit: &Unit) -> String {
    let mut out = String::new();
    writeln!(out, "// Code generated by compylr. DO NOT EDIT.").unwrap();
    writeln!(out, "package main\n").unwrap();

    // Emit Classes
    for class in unit.classes() {
        emit_class(class, &mut out);
    }

    // Emit Functions
    for function in unit.functions() {
        emit_function(function, &mut out);
    }

    out
}

fn emit_class(class: &Class, out: &mut String) {
    let class_name = go_ident(&class.name);

    // Struct definition
    writeln!(out, "type {} struct {{", class_name).unwrap();
    for attr in &class.attributes {
        writeln!(out, "\t{} {}", go_ident(&attr.name), go_ty(&attr.ty)).unwrap();
    }
    writeln!(out, "}}\n").unwrap();

    // Constructor
    let params_str = class
        .init
        .params
        .iter()
        .map(|p| format!("{} {}", go_ident(&p.name), go_ty(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "func New{}({}) *{} {{",
        class_name, params_str, class_name
    )
    .unwrap();
    writeln!(out, "\tinst := &{}{{", class_name).unwrap();
    for attr in &class.attributes {
        let name = go_ident(&attr.name);
        if class.init.params.iter().any(|p| p.name == attr.name) {
            writeln!(out, "\t\t{}: {},", name, name).unwrap();
        } else {
            let zero = match &attr.ty {
                Ty::Int => "0".to_string(),
                Ty::Float => "0.0".to_string(),
                Ty::Bool => "false".to_string(),
                Ty::Str => "\"\"".to_string(),
                Ty::List(t) => format!("make([]{}, 0)", go_ty(t)),
                Ty::Dict(k, v) => format!("make(map[{}]{})", go_ty(k), go_ty(v)),
                Ty::Set(t) => format!("make(map[{}]struct{{}})", go_ty(t)),
                _ => "nil".to_string(),
            };
            writeln!(out, "\t\t{}: {},", name, zero).unwrap();
        }
    }
    writeln!(out, "\t}}").unwrap();
    writeln!(out, "\treturn inst").unwrap();
    writeln!(out, "}}\n").unwrap();

    // Methods
    for method in class.methods.values() {
        emit_method(&class_name, method, out);
    }
}

fn emit_method(class_name: &str, method: &Function, out: &mut String) {
    let method_name = go_ident(&method.name);
    let params_str = method
        .params
        .iter()
        .map(|p| format!("{} {}", go_ident(&p.name), go_ty(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let ret_str = if method.ret == Ty::Unit {
        "".to_string()
    } else {
        format!(" {}", go_ty(&method.ret))
    };

    writeln!(
        out,
        "func (self *{}) {}({}){} {{",
        class_name, method_name, params_str, ret_str
    )
    .unwrap();
    let mut var_types = std::collections::HashMap::new();
    for p in &method.params {
        var_types.insert(p.name.clone(), p.ty.clone());
    }
    for stmt in &method.body {
        emit_stmt(stmt, out, 1, &mut var_types);
    }
    writeln!(out, "}}\n").unwrap();
}

fn emit_function(function: &Function, out: &mut String) {
    let fn_name = go_ident(&function.name);
    let params_str = function
        .params
        .iter()
        .map(|p| format!("{} {}", go_ident(&p.name), go_ty(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let ret_str = if function.ret == Ty::Unit {
        "".to_string()
    } else {
        format!(" {}", go_ty(&function.ret))
    };

    writeln!(out, "func {}({}){} {{", fn_name, params_str, ret_str).unwrap();
    let mut var_types = std::collections::HashMap::new();
    for p in &function.params {
        var_types.insert(p.name.clone(), p.ty.clone());
    }
    for stmt in &function.body {
        emit_stmt(stmt, out, 1, &mut var_types);
    }
    writeln!(out, "}}\n").unwrap();
}

fn emit_stmt(
    stmt: &Stmt,
    out: &mut String,
    indent: usize,
    var_types: &mut std::collections::HashMap<String, Ty>,
) {
    let ind = "\t".repeat(indent);
    match stmt {
        Stmt::Bind { name, ty, value } => {
            var_types.insert(name.clone(), ty.clone());
            if matches!(value, Expr::DictLit(p) if p.is_empty())
                || matches!(value, Expr::SetLit(e) if e.is_empty())
            {
                writeln!(
                    out,
                    "{}var {} {} = make({})",
                    ind,
                    go_ident(name),
                    go_ty(ty),
                    go_ty(ty)
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "{}var {} {} = {}",
                    ind,
                    go_ident(name),
                    go_ty(ty),
                    emit_expr(value)
                )
                .unwrap();
            }
        }
        Stmt::Assign { name, value, .. } => {
            writeln!(out, "{}{} = {}", ind, go_ident(name), emit_expr(value)).unwrap();
        }
        Stmt::SetAttr {
            object,
            name,
            value,
            ..
        } => {
            writeln!(
                out,
                "{}{}.{} = {}",
                ind,
                emit_expr(object),
                go_ident(name),
                emit_expr(value)
            )
            .unwrap();
        }
        Stmt::SetItem {
            collection,
            index,
            value,
        } => {
            writeln!(
                out,
                "{}{}[{}] = {}",
                ind,
                emit_expr(collection),
                emit_expr(index),
                emit_expr(value)
            )
            .unwrap();
        }
        Stmt::Append { sequence, value } => {
            let is_set = match sequence {
                Expr::Name(id) => matches!(var_types.get(id), Some(Ty::Set(_))),
                _ => false,
            };
            if is_set {
                writeln!(
                    out,
                    "{}{}[{}] = struct{{}}{{}}",
                    ind,
                    emit_expr(sequence),
                    emit_expr(value)
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "{}{} = append({}, {})",
                    ind,
                    emit_expr(sequence),
                    emit_expr(sequence),
                    emit_expr(value)
                )
                .unwrap();
            }
        }
        Stmt::Return(expr) => {
            writeln!(out, "{}return {}", ind, emit_expr(expr)).unwrap();
        }
        Stmt::ReturnUnit => {
            writeln!(out, "{}return", ind).unwrap();
        }
        Stmt::If {
            test,
            then,
            otherwise,
        } => {
            writeln!(out, "{}if {} {{", ind, emit_expr(test)).unwrap();
            let mut then_types = var_types.clone();
            for s in then {
                emit_stmt(s, out, indent + 1, &mut then_types);
            }
            if !otherwise.is_empty() {
                writeln!(out, "{}}} else {{", ind).unwrap();
                let mut else_types = var_types.clone();
                for s in otherwise {
                    emit_stmt(s, out, indent + 1, &mut else_types);
                }
            }
            writeln!(out, "{}}}", ind).unwrap();
        }
        Stmt::While { test, body } => {
            writeln!(out, "{}for {} {{", ind, emit_expr(test)).unwrap();
            let mut loop_types = var_types.clone();
            for s in body {
                emit_stmt(s, out, indent + 1, &mut loop_types);
            }
            writeln!(out, "{}}}", ind).unwrap();
        }
        Stmt::For {
            name,
            ty,
            iter,
            body,
        } => {
            let is_map_or_set = match iter {
                Expr::Name(id) => {
                    matches!(var_types.get(id), Some(Ty::Dict(_, _)) | Some(Ty::Set(_)))
                }
                _ => false,
            };
            if is_map_or_set {
                writeln!(
                    out,
                    "{}for {} := range {} {{",
                    ind,
                    go_ident(name),
                    emit_expr(iter)
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "{}for _, {} := range {} {{",
                    ind,
                    go_ident(name),
                    emit_expr(iter)
                )
                .unwrap();
            }
            let mut loop_types = var_types.clone();
            loop_types.insert(name.clone(), ty.clone());
            for s in body {
                emit_stmt(s, out, indent + 1, &mut loop_types);
            }
            writeln!(out, "{}}}", ind).unwrap();
        }
        Stmt::Break => {
            writeln!(out, "{}break", ind).unwrap();
        }
        Stmt::Continue => {
            writeln!(out, "{}continue", ind).unwrap();
        }
        Stmt::Effect(expr) => {
            if matches!(expr, Expr::MethodCall { .. } | Expr::Call { .. }) {
                writeln!(out, "{}{}", ind, emit_expr(expr)).unwrap();
            } else {
                writeln!(out, "{}_ = {}", ind, emit_expr(expr)).unwrap();
            }
        }
    }
}

fn emit_expr(expr: &Expr) -> String {
    match expr {
        Expr::Literal(lit) => match lit {
            Literal::Int(i) => format!("int64({})", i),
            Literal::Float(f) => format!("float64({:?})", f64::from_bits(*f)),
            Literal::Bool(b) => format!("{}", b),
            Literal::Str(s) => format!("{:?}", s),
        },
        Expr::Name(n) => {
            if n == "self" {
                "self".to_string()
            } else {
                go_ident(n)
            }
        }
        Expr::Neg { value, .. } => format!("-({})", emit_expr(value)),
        Expr::Not(e) => format!("!({})", emit_expr(e)),
        Expr::ToFloat(e) => format!("float64({})", emit_expr(e)),
        Expr::Binary { op, left, right } => {
            let l = emit_expr(left);
            let r = emit_expr(right);
            match op {
                BinOp::Add { .. } => format!("({} + {})", l, r),
                BinOp::Sub { .. } => format!("({} - {})", l, r),
                BinOp::Mul { .. } => format!("({} * {})", l, r),
                BinOp::Div {
                    mode: DivMode::Integer(_),
                    ..
                } => format!("GoFloorDiv({}, {})", l, r),
                BinOp::Div { .. } => format!("({} / {})", l, r),
                BinOp::Rem { .. } => format!("GoRem({}, {})", l, r),
                BinOp::Eq => format!("({} == {})", l, r),
                BinOp::NotEq => format!("({} != {})", l, r),
                BinOp::Lt => format!("({} < {})", l, r),
                BinOp::LtE => format!("({} <= {})", l, r),
                BinOp::Gt => format!("({} > {})", l, r),
                BinOp::GtE => format!("({} >= {})", l, r),
            }
        }
        Expr::Subscript { base, index, .. } => {
            format!("({})[{}]", emit_expr(base), emit_expr(index))
        }
        Expr::Attribute { object, name } => format!("{}.{}", emit_expr(object), go_ident(name)),
        Expr::Len { value, .. } => format!("int64(len({}))", emit_expr(value)),
        Expr::Call { callee, args } => {
            let args_str = args.iter().map(emit_expr).collect::<Vec<_>>().join(", ");
            format!("{}({})", go_ident(callee), args_str)
        }
        Expr::MethodCall {
            receiver,
            method,
            args,
            ..
        } => {
            let args_str = args.iter().map(emit_expr).collect::<Vec<_>>().join(", ");
            format!("{}.{}({})", emit_expr(receiver), go_ident(method), args_str)
        }
        Expr::Construct { class, args } => {
            let args_str = args.iter().map(emit_expr).collect::<Vec<_>>().join(", ");
            format!("New{}({})", go_ident(class), args_str)
        }
        Expr::ListLit(elements) => {
            if elements.is_empty() {
                "nil".to_string()
            } else {
                let elems_str = elements
                    .iter()
                    .map(emit_expr)
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("[]int64{{ {} }}", elems_str)
            }
        }
        Expr::TupleLit(elements) => {
            let type_fields = elements
                .iter()
                .enumerate()
                .map(|(i, _)| format!("F{} int64", i))
                .collect::<Vec<_>>()
                .join("; ");
            let val_fields = elements
                .iter()
                .enumerate()
                .map(|(i, e)| format!("F{}: {}", i, emit_expr(e)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("struct {{ {} }}{{ {} }}", type_fields, val_fields)
        }
        Expr::Contains { value, container } => {
            format!(
                "func() bool {{ _, ok := ({})[{}]; return ok }}()",
                emit_expr(container),
                emit_expr(value)
            )
        }
        Expr::DictLit(pairs) => {
            if pairs.is_empty() {
                "nil".to_string()
            } else {
                let pairs_str = pairs
                    .iter()
                    .map(|(k, v)| format!("{}: {}", emit_expr(k), emit_expr(v)))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("map[int64]int64{{ {} }}", pairs_str)
            }
        }
        Expr::SetLit(elements) => {
            if elements.is_empty() {
                "nil".to_string()
            } else {
                let elems_str = elements
                    .iter()
                    .map(|e| format!("{}: struct{{}}{{}}", emit_expr(e)))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("map[string]struct{{}}{{ {} }}", elems_str)
            }
        }
        Expr::TupleIndex { base, position } => {
            format!("{}.F{}", emit_expr(base), position)
        }
        _ => "/* unsupported expr */".to_string(),
    }
}
