[workspace]

[package]
name = "compylr_generated_ef5b5f0fa0049bdd_a0cdd1db"
version = "0.1.0"
edition = "2024"

[lib]
name = "compylr_generated_ef5b5f0fa0049bdd_a0cdd1db"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29.2", features = ["abi3-py311", "extension-module"] }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "unwind"
