//! The PyO3 layer wrapping compiled functions.
//!
//! Kept apart from `rust.rs` on purpose: that module knows how to translate IR into Rust and
//! nothing about Python, so the same translation could feed a non-Python consumer. This module is
//! the only place where Rust values become Python values and where a [`RuntimeError`] becomes an
//! exception.
//!
//! [`RuntimeError`]: super::runtime::RuntimeError
//!
//! The wrappers are thin by design. Each one calls the pure function, maps its error, and returns
//! — no logic that could disagree with the translated body.

use std::fmt::Write as _;

use compylr_backend_rust::rust::{LIB_PATH, RustBackend, rust_ident, rust_ty};

use crate::BINDINGS_PATH;
use compylr_core::backend::{Backend, BackendError, GeneratedFiles};
use compylr_ir::{Class, Ty, Unit};

/// Prefix for the extension module a unit compiles to.
const MODULE_PREFIX: &str = "compylr_generated_";

/// The Python module name a unit compiles to.
///
/// The fingerprint is part of the name because CPython cannot reliably re-import an extension
/// module under a name already present in `sys.modules` — the shared object is already mapped, and
/// reload semantics for extension modules are not supported. A fixed name would therefore make a
/// rebuild inside a running process succeed and then be unloadable. Each build producing a
/// distinct module sidesteps that entirely.
///
/// This is safe only because the name is never user-facing: callers reach compiled functions
/// through the objects they decorated, never by importing this module themselves.
pub fn module_name(unit: &Unit) -> String {
    format!("{MODULE_PREFIX}{:016x}", unit.fingerprint())
}

/// Emit a complete extension-module crate for a unit.
///
/// The pure translation from [`RustBackend`] plus a binding layer in its own file, so the two
/// stay separable and the translated bodies are identical whether or not Python is involved.
/// `lib.rs` gains the extra module declaration and the module registration.
pub fn emit_extension(unit: &Unit) -> Result<GeneratedFiles, BackendError> {
    let mut files = RustBackend.emit(unit)?;
    files.insert(BINDINGS_PATH.to_string(), emit_binding_layer(unit)?);
    files.insert(LIB_PATH.to_string(), emit_extension_root(unit));
    Ok(files)
}

/// The crate root for an extension module.
///
/// Registration delegates to `bindings::register` rather than naming each wrapper, so this file
/// is the same size whether the project compiles one function or fifty — and so that
/// `wrap_pyfunction!` never has to resolve a path across a module boundary.
fn emit_extension_root(unit: &Unit) -> String {
    format!(
        "// Generated by compylr. Do not edit: regenerated from the IR on every rebuild.\n\
         #![allow(unused_parens, non_snake_case, unused_variables, dead_code, unused_imports, unused_assignments)]\n\
         \n\
         use pyo3::prelude::*;\n\
         \n\
         pub mod bindings;\n\
         pub mod compat;\n\
         pub mod generated;\n\
         \n\
         #[pymodule]\n\
         fn {}(m: &Bound<'_, PyModule>) -> PyResult<()> {{\n\
         {}bindings::register(m)\n\
         }}\n",
        module_name(unit),
        "    "
    )
}

/// The PyO3 wrappers and the module registration.
fn emit_binding_layer(unit: &Unit) -> Result<String, BackendError> {
    let mut out = String::new();
    out.push_str(PREAMBLE);

    for (index, class) in unit.classes().enumerate() {
        out.push_str(&emit_class_binding(index, class));
    }

    for (index, function) in unit.functions().enumerate() {
        let params = function
            .params
            .iter()
            .map(|p| format!("{}: {}", rust_ident(&p.name), rust_ty(&p.ty)))
            .collect::<Vec<_>>()
            .join(", ");
        let args = function
            .params
            .iter()
            .map(|p| rust_ident(&p.name))
            .collect::<Vec<_>>()
            .join(", ");

        // The wrapper is named positionally rather than after the function. A Python name can be
        // a Rust keyword, and `#[pyo3(name = ...)]` is what restores the name Python sees, so the
        // Rust-side identifier only has to be unique.
        let _ = writeln!(out, "#[pyfunction]");
        let _ = writeln!(out, "#[pyo3(name = {:?})]", function.name);
        let _ = writeln!(
            out,
            "fn __compylr_export_{index}({params}) -> PyResult<{}> {{",
            rust_ty(&function.ret)
        );
        let _ = writeln!(
            out,
            "    generated::{}({args}).map_err(__compylr_to_py_err)",
            rust_ident(&function.name)
        );
        out.push_str("}\n\n");
    }

    let _ = writeln!(
        out,
        "/// Register every compiled function on the module.\n\
         ///\n\
         /// Kept here rather than in the crate root so that `wrap_pyfunction!` resolves the\n\
         /// wrappers locally, and so the root stays the same size for any number of functions.\n\
         pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {{"
    );
    for index in 0..unit.classes().count() {
        let _ = writeln!(out, "    m.add_class::<__compylr_class_{index}>()?;");
    }
    for index in 0..unit.len() {
        let _ = writeln!(
            out,
            "    m.add_function(wrap_pyfunction!(__compylr_export_{index}, m)?)?;"
        );
    }
    out.push_str("    Ok(())\n}\n");

    // A unit type is only valid as a return, so nothing above can have produced a `()` parameter.
    debug_assert!(
        unit.functions()
            .all(|f| f.params.iter().all(|p| p.ty != Ty::Unit))
    );
    Ok(out)
}

/// Expose one class to Python.
///
/// The wrapper holds the translated struct rather than being it, so `generated.rs` stays free of
/// PyO3 and could feed a non-Python consumer unchanged.
///
/// This is what makes instance state work, and it is worth contrasting with collections. A
/// collection **argument** is converted by value at the boundary, so a compiled function cannot
/// mutate its caller's list. An instance is not converted at all — the Python object *holds* the
/// Rust value, and a method borrows it from there — so a mutated attribute is exactly what the
/// caller sees on the next call. That asymmetry is why an attribute can be a cache while a
/// parameter cannot be mutated.
fn emit_class_binding(index: usize, class: &Class) -> String {
    let mut out = String::new();
    let wrapper = format!("__compylr_class_{index}");
    let translated = rust_ident(&class.name);
    let mutating = compylr_backend_rust::rust::mutating_methods(class);

    if let Some(doc) = &class.doc {
        for line in doc.lines() {
            let _ = writeln!(out, "/// {line}");
        }
    }
    // Named positionally for the same reason the function wrappers are: a Python class name can be
    // a Rust keyword, and `#[pyclass(name = ...)]` is what restores the name Python sees.
    let _ = writeln!(out, "#[pyclass(name = {:?})]", class.name);
    let _ = writeln!(out, "pub struct {wrapper} {{");
    let _ = writeln!(out, "    inner: generated::{translated},");
    out.push_str("}\n\n");

    let _ = writeln!(out, "#[pymethods]");
    let _ = writeln!(out, "impl {wrapper} {{");

    let params = class
        .init
        .params
        .iter()
        .map(|p| format!("{}: {}", rust_ident(&p.name), rust_ty(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let args = class
        .init
        .params
        .iter()
        .map(|p| rust_ident(&p.name))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(out, "    #[new]");
    let _ = writeln!(out, "    fn __compylr_init({params}) -> PyResult<Self> {{");
    let _ = writeln!(
        out,
        "        Ok(Self {{ inner: generated::{translated}::__compylr_new({args})\
         .map_err(__compylr_to_py_err)? }})"
    );
    out.push_str("    }\n");

    for (position, method) in class.methods.values().enumerate() {
        let receiver = if mutating.contains(&method.name) {
            "&mut self"
        } else {
            "&self"
        };
        let params = method
            .params
            .iter()
            .map(|p| format!("{}: {}", rust_ident(&p.name), rust_ty(&p.ty)))
            .collect::<Vec<_>>()
            .join(", ");
        let separator = if params.is_empty() { "" } else { ", " };
        let args = method
            .params
            .iter()
            .map(|p| rust_ident(&p.name))
            .collect::<Vec<_>>()
            .join(", ");

        out.push('\n');
        if let Some(doc) = &method.doc {
            for line in doc.lines() {
                let _ = writeln!(out, "    /// {line}");
            }
        }
        let _ = writeln!(out, "    #[pyo3(name = {:?})]", method.name);
        let _ = writeln!(
            out,
            "    fn __compylr_method_{index}_{position}({receiver}{separator}{params}) \
             -> PyResult<{}> {{",
            rust_ty(&method.ret)
        );
        let _ = writeln!(
            out,
            "        self.inner.{}({args}).map_err(__compylr_to_py_err)",
            rust_ident(&method.name)
        );
        out.push_str("    }\n");
    }
    out.push_str("}\n\n");
    out
}

/// Imports and the error mapping shared by every wrapper.
///
/// The mapping is where compylr's promise of "same semantics" is actually kept at the boundary:
/// code that already catches `ZeroDivisionError` around a function keeps working when that
/// function is compiled, because the compiled version raises the same thing.
const PREAMBLE: &str = r#"//! The Python boundary for the translated functions.

use std::collections::{HashMap, HashSet};

use pyo3::exceptions::{
    PyIndexError, PyKeyError, PyOverflowError, PyValueError, PyZeroDivisionError,
};
use pyo3::prelude::*;

use crate::compat::RuntimeError;
use crate::generated;

/// Map a compiled function's failure onto the exception Python raises for the same condition.
fn __compylr_to_py_err(error: RuntimeError) -> PyErr {
    match error {
        RuntimeError::DivisionByZero => PyZeroDivisionError::new_err("division by zero"),
        RuntimeError::Overflow => {
            PyOverflowError::new_err("integer arithmetic overflowed a 64-bit signed integer")
        }
        RuntimeError::IndexOutOfRange => PyIndexError::new_err("index out of range"),
        RuntimeError::ZeroStep => PyValueError::new_err("range() arg 3 must not be zero"),
        RuntimeError::MissingKey(key) => PyKeyError::new_err(key),
    }
}

"#;

/// `Cargo.toml` for the generated crate.
///
/// The crate depends on `pyo3` and nothing else — deliberately not on compylr, which will not
/// exist on the machine where this is built.
pub fn cargo_manifest(unit: &Unit, pyo3_version: &str) -> String {
    let name = module_name(unit);
    format!(
        // The empty `[workspace]` table makes this crate its own workspace root. Without it,
        // a generated crate written anywhere inside a Cargo workspace — a user's project, or
        // this repo's own `target/` — is adopted as a member and fails to build, complaining
        // that it believes it is in a workspace when it is not.
        "[workspace]\n\
         \n\
         [package]\n\
         name = \"{name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2024\"\n\
         \n\
         [lib]\n\
         name = \"{name}\"\n\
         crate-type = [\"cdylib\"]\n\
         \n\
         [dependencies]\n\
         pyo3 = {{ version = \"{pyo3_version}\", features = [\"abi3-py311\", \"extension-module\"] }}\n"
    )
}
