//! The PyO3 layer wrapping compiled functions.
//!
//! Kept apart from `rust.rs` on purpose: that module knows how to translate IR into Rust and
//! nothing about Python, so the same translation could feed a non-Python consumer. This module is
//! the only place where Rust values become Python values and where a [`RuntimeError`] becomes an
//! exception.
//!
//! [`RuntimeError`]: super::runtime::RuntimeError
//!
//! The wrappers are thin by design. Each one calls the pure function, maps its error, and returns
//! — no logic that could disagree with the translated body.

use std::fmt::Write as _;

use compylr_backend_rust::rust::{LIB_PATH, RustBackend, rust_ident, rust_param_ty, rust_ty};

use crate::BINDINGS_PATH;
use compylr_core::backend::{Backend, BackendError, GeneratedFiles};
use compylr_core::bridge::BuildKey;
use compylr_ir::{Class, Ty, Unit};

/// Prefix for the extension module a unit compiles to.
const MODULE_PREFIX: &str = "compylr_generated_";

/// The Python module name a unit compiles to.
///
/// The fingerprint is part of the name because CPython cannot reliably re-import an extension
/// module under a name already present in `sys.modules` — the shared object is already mapped, and
/// reload semantics for extension modules are not supported. A fixed name would therefore make a
/// rebuild inside a running process succeed and then be unloadable. Each build producing a
/// distinct module sidesteps that entirely.
///
/// This is safe only because the name is never user-facing: callers reach compiled functions
/// through the objects they decorated, never by importing this module themselves.
pub fn module_name(key: &BuildKey) -> String {
    format!(
        "{MODULE_PREFIX}{:016x}_{}",
        key.fingerprint,
        key.variant_tag()
    )
}

/// Emit a complete extension-module crate for a unit.
///
/// The pure translation from [`RustBackend`] plus a binding layer in its own file, so the two
/// stay separable and the translated bodies are identical whether or not Python is involved.
/// `lib.rs` gains the extra module declaration and the module registration.
pub fn emit_extension(unit: &Unit, key: &BuildKey) -> Result<GeneratedFiles, BackendError> {
    let mut files = RustBackend.emit(unit)?;
    files.insert(BINDINGS_PATH.to_string(), emit_binding_layer(unit)?);
    files.insert(LIB_PATH.to_string(), emit_extension_root(key));
    Ok(files)
}

/// The crate root for an extension module.
///
/// Registration delegates to `bindings::register` rather than naming each wrapper, so this file
/// is the same size whether the project compiles one function or fifty — and so that
/// `wrap_pyfunction!` never has to resolve a path across a module boundary.
fn emit_extension_root(key: &BuildKey) -> String {
    format!(
        "// Generated by compylr. Do not edit: regenerated from the IR on every rebuild.\n\
         #![allow(unused_parens, non_snake_case, unused_variables, dead_code, unused_imports, unused_assignments)]\n\
         \n\
         use pyo3::prelude::*;\n\
         \n\
         pub mod bindings;\n\
         pub mod compat;\n\
         pub mod generated;\n\
         \n\
         #[pymodule]\n\
         fn {}(m: &Bound<'_, PyModule>) -> PyResult<()> {{\n\
         {}bindings::register(m)\n\
         }}\n",
        module_name(key),
        "    "
    )
}

/// The PyO3 wrappers and the module registration.
fn emit_binding_layer(unit: &Unit) -> Result<String, BackendError> {
    let mut out = String::new();
    out.push_str(PREAMBLE);

    for (index, class) in unit.classes().enumerate() {
        out.push_str(&emit_class_binding(index, class, unit));
    }

    for (index, function) in unit.functions().enumerate() {
        let params = function
            .params
            .iter()
            .map(|p| {
                format!(
                    "{}: {}",
                    rust_ident(&p.name),
                    rust_param_ty(function, p, unit)
                )
            })
            .collect::<Vec<_>>()
            .join(", ");
        let args = function
            .params
            .iter()
            .map(|p| rust_ident(&p.name))
            .collect::<Vec<_>>()
            .join(", ");

        // The wrapper is named positionally rather than after the function. A Python name can be
        // a Rust keyword, and `#[pyo3(name = ...)]` is what restores the name Python sees, so the
        // Rust-side identifier only has to be unique.
        let _ = writeln!(out, "#[pyfunction]");
        let _ = writeln!(out, "#[pyo3(name = {:?})]", function.name);
        let _ = writeln!(
            out,
            "fn __compylr_export_{index}({params}) -> PyResult<{}> {{",
            rust_ty(&function.ret)
        );
        let _ = writeln!(
            out,
            "    generated::{}({args}).map_err(__compylr_to_py_err)",
            rust_ident(&function.name)
        );
        out.push_str("}\n\n");
    }

    let _ = writeln!(
        out,
        "/// Register every compiled function on the module.\n\
         ///\n\
         /// Kept here rather than in the crate root so that `wrap_pyfunction!` resolves the\n\
         /// wrappers locally, and so the root stays the same size for any number of functions.\n\
         pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {{"
    );
    for index in 0..unit.classes().count() {
        let _ = writeln!(out, "    m.add_class::<__compylr_class_{index}>()?;");
    }
    for index in 0..unit.len() {
        let _ = writeln!(
            out,
            "    m.add_function(wrap_pyfunction!(__compylr_export_{index}, m)?)?;"
        );
    }
    out.push_str("    Ok(())\n}\n");

    // A unit type is only valid as a return, so nothing above can have produced a `()` parameter.
    debug_assert!(
        unit.functions()
            .all(|f| f.params.iter().all(|p| p.ty != Ty::Unit))
    );
    Ok(out)
}

/// Expose one class to Python.
///
/// The wrapper holds the translated struct rather than being it, so `generated.rs` stays free of
/// PyO3 and could feed a non-Python consumer unchanged.
///
/// This is what makes instance state work, and it is worth contrasting with collections. A
/// collection **argument** is converted by value at the boundary, so a compiled function cannot
/// mutate its caller's list. An instance is not converted at all — the Python object *holds* the
/// Rust value, and a method borrows it from there — so a mutated attribute is exactly what the
/// caller sees on the next call. That asymmetry is why an attribute can be a cache while a
/// parameter cannot be mutated.
fn emit_class_binding(index: usize, class: &Class, unit: &Unit) -> String {
    let mut out = String::new();
    let wrapper = format!("__compylr_class_{index}");
    let translated = rust_ident(&class.name);
    let mutating = compylr_backend_rust::rust::mutating_methods(class);

    if let Some(doc) = &class.doc {
        for line in doc.lines() {
            let _ = writeln!(out, "/// {line}");
        }
    }
    // Named positionally for the same reason the function wrappers are: a Python class name can be
    // a Rust keyword, and `#[pyclass(name = ...)]` is what restores the name Python sees.
    let _ = writeln!(out, "#[pyclass(name = {:?})]", class.name);
    let _ = writeln!(out, "pub struct {wrapper} {{");
    let _ = writeln!(out, "    inner: generated::{translated},");
    out.push_str("}\n\n");

    let _ = writeln!(out, "#[pymethods]");
    let _ = writeln!(out, "impl {wrapper} {{");

    let params = class
        .init
        .params
        .iter()
        .map(|p| format!("{}: {}", rust_ident(&p.name), rust_ty(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let args = class
        .init
        .params
        .iter()
        .map(|p| rust_ident(&p.name))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(out, "    #[new]");
    let _ = writeln!(out, "    fn __compylr_init({params}) -> PyResult<Self> {{");
    let _ = writeln!(
        out,
        "        Ok(Self {{ inner: generated::{translated}::__compylr_new({args})\
         .map_err(__compylr_to_py_err)? }})"
    );
    out.push_str("    }\n");

    for (position, method) in class.methods.values().enumerate() {
        let receiver = if mutating.contains(&method.name) {
            "&mut self"
        } else {
            "&self"
        };
        let params = method
            .params
            .iter()
            .map(|p| {
                format!(
                    "{}: {}",
                    rust_ident(&p.name),
                    rust_param_ty(method, p, unit)
                )
            })
            .collect::<Vec<_>>()
            .join(", ");
        let separator = if params.is_empty() { "" } else { ", " };
        let args = method
            .params
            .iter()
            .map(|p| rust_ident(&p.name))
            .collect::<Vec<_>>()
            .join(", ");

        out.push('\n');
        if let Some(doc) = &method.doc {
            for line in doc.lines() {
                let _ = writeln!(out, "    /// {line}");
            }
        }
        let _ = writeln!(out, "    #[pyo3(name = {:?})]", method.name);
        let _ = writeln!(
            out,
            "    fn __compylr_method_{index}_{position}({receiver}{separator}{params}) \
             -> PyResult<{}> {{",
            rust_ty(&method.ret)
        );
        let _ = writeln!(
            out,
            "        self.inner.{}({args}).map_err(__compylr_to_py_err)",
            rust_ident(&method.name)
        );
        out.push_str("    }\n");
    }
    out.push_str("}\n\n");
    out
}

/// Imports and the error mapping shared by every wrapper.
///
/// The mapping is where compylr's promise of "same semantics" is actually kept at the boundary:
/// code that already catches `ZeroDivisionError` around a function keeps working when that
/// function is compiled, because the compiled version raises the same thing.
const PREAMBLE: &str = r#"//! The Python boundary for the translated functions.

// The hashed containers come from the runtime rather than from `std`. A wrapper signature has to
// name the same type the translated function does, and `std`'s aliases pin the default hasher.
use crate::compat::{FastMap, FastSet};

use pyo3::exceptions::{
    PyIndexError, PyKeyError, PyOverflowError, PyValueError, PyZeroDivisionError,
};
use pyo3::prelude::*;

use crate::compat::RuntimeError;
use crate::generated;

/// Map a compiled function's failure onto the exception Python raises for the same condition.
fn __compylr_to_py_err(error: RuntimeError) -> PyErr {
    match error {
        RuntimeError::DivisionByZero => PyZeroDivisionError::new_err("division by zero"),
        RuntimeError::Overflow => {
            PyOverflowError::new_err("integer arithmetic overflowed a 64-bit signed integer")
        }
        RuntimeError::IndexOutOfRange => PyIndexError::new_err("index out of range"),
        RuntimeError::ZeroStep => PyValueError::new_err("range() arg 3 must not be zero"),
        RuntimeError::MissingKey(key) => PyKeyError::new_err(key),
    }
}

"#;

/// `Cargo.toml` for the generated crate.
///
/// The crate depends on `pyo3` and nothing else — deliberately not on compylr, which will not
/// exist on the machine where this is built.
///
/// The release profile is declared rather than inherited. The artifact is built **once per
/// fingerprint** and imported on every run after that, so build time is the cheap side of that
/// trade and run time is the expensive one; Cargo's defaults are tuned for the opposite. It costs
/// roughly 7-10s more on the demo's crate and is recovered on every call thereafter.
pub fn cargo_manifest(key: &BuildKey, pyo3_version: &str) -> String {
    let name = module_name(key);
    format!(
        // The empty `[workspace]` table makes this crate its own workspace root. Without it,
        // a generated crate written anywhere inside a Cargo workspace — a user's project, or
        // this repo's own `target/` — is adopted as a member and fails to build, complaining
        // that it believes it is in a workspace when it is not.
        "[workspace]\n\
         \n\
         [package]\n\
         name = \"{name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2024\"\n\
         \n\
         [lib]\n\
         name = \"{name}\"\n\
         crate-type = [\"cdylib\"]\n\
         \n\
         [dependencies]\n\
         pyo3 = {{ version = \"{pyo3_version}\", features = [\"abi3-py311\", \"extension-module\"] }}\n\
         \n\
         # Declared, not inherited. The runtime helpers are emitted into a different module from\n\
         # the code that calls them, and at Cargo's default of sixteen codegen units they are\n\
         # frequently not inlined — which matters here in particular because every arithmetic\n\
         # operation in the supported subset is a trait call by design.\n\
         #\n\
         # `panic` is stated rather than left to default: the bridge turns a panic into a Python\n\
         # exception, and aborting would terminate the interpreter instead.\n\
         #\n\
         # No `target-cpu`. It was measured and moved no row outside the benchmark's noise floor,\n\
         # and a generated crate may be copied to a machine whose CPU lacks the instructions it\n\
         # was built for. A slower artifact beats one that faults.\n\
         [profile.release]\n\
         lto = \"fat\"\n\
         codegen-units = 1\n\
         panic = \"unwind\"\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key() -> BuildKey {
        BuildKey {
            fingerprint: 0x1234_5678_9abc_def0,
            target: "rust".to_string(),
            passes: "default".to_string(),
        }
    }

    /// The manifest with its comments removed: what Cargo actually reads.
    ///
    /// The comments explain why a setting was rejected, and so they name the very things the
    /// assertions below forbid. Matching raw text would make an explanation indistinguishable
    /// from a directive — and would punish documenting the decision.
    fn directives(manifest: &str) -> String {
        manifest
            .lines()
            .filter(|line| !line.trim_start().starts_with('#'))
            .collect::<Vec<_>>()
            .join("\n")
    }

    /// The artifact is built once per fingerprint and imported on every run after that, so build
    /// time is the cheap side of the trade and run time is the expensive one. Cargo's defaults
    /// optimize for the opposite.
    #[test]
    fn the_manifest_declares_a_release_profile() {
        let manifest = cargo_manifest(&key(), "0.29.2");
        assert!(
            manifest.contains("[profile.release]"),
            "no release profile in:\n{manifest}"
        );
    }

    /// The runtime helpers are emitted into a different module from the code that calls them, and
    /// at Cargo's default of sixteen codegen units they are frequently not inlined. That matters
    /// here in particular because every arithmetic operation in the subset is a trait call by
    /// design.
    #[test]
    fn the_release_profile_asks_for_link_time_optimization_and_one_codegen_unit() {
        let manifest = cargo_manifest(&key(), "0.29.2");
        assert!(manifest.contains("lto = "), "no lto in:\n{manifest}");
        assert!(
            manifest.contains("codegen-units = 1"),
            "not one codegen unit in:\n{manifest}"
        );
    }

    /// The bridge converts a panic into a Python exception. Aborting would terminate the
    /// interpreter instead, so unwinding is written out explicitly rather than left to the
    /// default — a default is something a later change can flip without noticing what it cost.
    #[test]
    fn the_release_profile_preserves_unwinding() {
        let manifest = cargo_manifest(&key(), "0.29.2");
        assert!(
            manifest.contains("panic = \"unwind\""),
            "unwinding not stated in:\n{manifest}"
        );
        assert!(
            !directives(&manifest).contains("abort"),
            "a generated crate may not abort: a panic has to reach Python as an exception:\n\
             {manifest}"
        );
    }

    /// Measured and rejected: no row moved outside the benchmark's noise floor, and a generated
    /// crate may be copied to another machine, where an artifact built for this CPU faults on an
    /// unsupported instruction. A slower artifact beats one that crashes.
    ///
    /// This assertion is the thing that stops it being re-added on the grounds that it is
    /// obviously free.
    #[test]
    fn the_manifest_pins_no_target_cpu() {
        let manifest = cargo_manifest(&key(), "0.29.2");
        assert!(
            !directives(&manifest).contains("target-cpu"),
            "a pinned target CPU makes a copied artifact fault elsewhere:\n{manifest}"
        );
    }

    /// The empty `[workspace]` table is what keeps a generated crate from being adopted as a
    /// member of whatever workspace it was written inside. Adding sections after it must not
    /// disturb that.
    #[test]
    fn the_crate_is_still_its_own_workspace_root() {
        let manifest = cargo_manifest(&key(), "0.29.2");
        assert!(manifest.starts_with("[workspace]\n"), "{manifest}");
    }

    /// Every section the build needs is still present, in a form Cargo will parse.
    #[test]
    fn the_manifest_still_declares_the_package_library_and_dependency() {
        let manifest = cargo_manifest(&key(), "0.29.2");
        for section in ["[package]", "[lib]", "[dependencies]"] {
            assert!(manifest.contains(section), "no {section} in:\n{manifest}");
        }
        assert!(manifest.contains("crate-type = [\"cdylib\"]"), "{manifest}");
        assert!(
            manifest.contains("pyo3 = { version = \"0.29.2\""),
            "{manifest}"
        );
    }
}
